---
title: "Capstone Data Manip Desc"
author: "Alex Wu"
date: "July 22, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Wine Ratings by Region, Price, and Variety
This data set contain over 150k lines of data of various wines accross the world.

Key points

- points are on a scale of 1 - 100
- maximum price of $99
- Wine is identified by 
    - Country
    - Province
    - Varietal
    - Winery
  

### Cleaning up the data

#### Importing the data
library(readxl)
winemag_data_130k_v2 <- read_excel("winemag-data-130k-v2.xlsx")
View(winemag_data_130k_v2)

library(dplyr)
library(tidyr)



#### Manipulating the data

DF <- winemag_data_130k_v2
DF %>% summary(price)


##### Price was missing. Filled it with median price
DF <- DF %>% mutate(`price` = ifelse(is.na(price), "25", price))



##### Removed columns of data that would not be used in analysis
DF3 <- DF[, c(1,2,5,6,7,13,14)]






##### Need to do
Add in sub categories with variety
Add in sub categories with Country
Create new plots with those additional categories


Useful formula
ggplot(WineList, aes(x=log(price))) + geom_histogram(aes(fill=country), alpha=0.40)
ggplot(WineList, aes(x=price)) + geom_histogram(aes(fill=variety), aes=0.4)
ggplot(wine_data, aes(x=price)) + geom_histogram(aes(fill=vareity), aes=0.4)


##### Notes 8/26
Make new price a new column

Use these for 
cut()
quantile()


Writes description in RMD with the script code. But also helps with 

2d density plot. It's a different function. Color by region, type, etc

Next Part
Exploratory Data parts
Identify key predictive factors
More visual models
Correlation matrix - Coreplot. Show correlation values


Scaling:
Square root transform. Square root of the count of wine by region
scale_y_continuous(trans="sqrt"

Take a look at ggplot documentation.

X = proportion of wine in total
y = rating
ggplot(new_df, aes(x=Prop, y=MeanPrice)) + geom_point(aes(shape=region, colour="region")



Correlation
dummy variable make the categories binary
There is a package that can make it binary
multiple columns of 1 or 0

Z scores, median, 
What does it mean

Distribution bell for wine type, price, variety, etc





Cut by region sub cuts


Exm <- WineList %>% group_by(price_cat)

